kvx: add missing kstat.h header
Summary: Building linux with musl support fails with

src/stat/fchmodat.c:5:10: fatal error:
kstat.h: No such file or directory

This revision provide the missing kstat.h header.

Test Plan: Buildroot + musl

Reviewers: O52 Linux libcs Coolidge!

Subscribers: #linux_coolidge_cc

Maniphest Tasks: T12378

Differential Revision: https://phab.kalray.eu/D15454